<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>NekoLib.Navigation.RuntimeTests.LoginFlow481</RootNamespace>
    <AssemblyName>NekoLib.Navigation.RuntimeTests.LoginFlow481</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Navigation\NekoLib.Navigation.WinForms\NekoLib.Navigation.WinForms.csproj" />
    <ProjectReference Include="..\..\..\src\Mvvm\NekoLib.Mvvm\NekoLib.Mvvm.csproj" />
  </ItemGroup>

</Project>
