<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net481;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>NekoLib.Http.RuntimeTests.TheCatApi</AssemblyName>
    <RootNamespace>NekoLib.Http.RuntimeTests.TheCatApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Http\NekoLib.Http\NekoLib.Http.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
