<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>

		<!-- Library -->
		<OutputType>Library</OutputType>

		<!-- Assembly info -->
		<AssemblyName>NekoLib.Data.Internal.Gateway</AssemblyName>
		<RootNamespace>NekoLib.Data.Internal.Gateway</RootNamespace>

		<!-- Identity -->
		<DefineConstants>$(DefineConstants);NEKOLIB</DefineConstants>
	</PropertyGroup>

  <!-- Referências condicionais -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <!-- net481: System.Data.SqlClient já vem no framework -->
    <Reference Include="System.Data" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net481'">
    <!-- net6+ / net9: use Microsoft.Data.SqlClient -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NekoLib.Data\NekoLib.Data.csproj" />
  </ItemGroup>

  <!-- Se você quiser publicar com trimming (net9) -->
  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <!-- use com cuidado: reflection exige anotações -->
    <PublishTrimmed>false</PublishTrimmed>
    <!-- Em apps AOT, DynamicMode.IL será bloqueado por guard -->
  </PropertyGroup>

</Project>
	 
	