<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0-windows</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>

		<OutputType>Library</OutputType>
		<AssemblyName>NekoLib.Diagnostics</AssemblyName>
		<RootNamespace>NekoLib.Diagnostics</RootNamespace>

		<!-- Assembly metadata: generated ONCE -->
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>

		<!-- CRITICAL: avoid duplicate TargetFrameworkAttribute -->
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

		<DefineConstants>$(DefineConstants);NEKOLIB</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0'">
		<DefineConstants>$(DefineConstants);NET_9</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net481'">
		<DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net481' Or '$(TargetFramework)' == 'net9.0-windows'">
		<UseWindowsForms>true</UseWindowsForms>
		<DefineConstants>$(DefineConstants);WINFORMS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);NET_9;WINFORMS</DefineConstants>
	</PropertyGroup>


	<ItemGroup>
		<Compile Include="..\NekoLib.Diagnostics.Abstractions\**\*.cs" Link="Abstractions\%(RecursiveDir)%(Filename)%(Extension)" Exclude="&#xA;             ..\NekoLib.Diagnostics.Abstractions\bin\**;&#xA;             ..\NekoLib.Diagnostics.Abstractions\obj\**;&#xA;             ..\NekoLib.Diagnostics.Abstractions\**\AssemblyInfo.cs;&#xA;             ..\NekoLib.Diagnostics.Abstractions\**\*AssemblyInfo*.cs;&#xA;             ..\NekoLib.Diagnostics.Abstractions\Properties\AssemblyInfo.cs;&#xA;             ..\NekoLib.Diagnostics.Abstractions\**\SharedAssemblyInfo.cs&#xA;           " />
	</ItemGroup>

</Project>
