<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0-windows</TargetFrameworks>

		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>

		<OutputType>Library</OutputType>

		<AssemblyName>NekoLib.Navigation.Wpf</AssemblyName>
		<RootNamespace>NekoLib.Navigation.Wpf</RootNamespace>

		<IsPackable>true</IsPackable>
		<PackageId>NekoLib.Navigation.Wpf</PackageId>
		<Title>NekoLib Navigation for WPF</Title>
		<Description>WPF host and platform adapters for NekoLib.Navigation.</Description>
		<PackageTags>nekolib;navigation;wpf;kiosk;pos</PackageTags>

		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NekoLib.Navigation\NekoLib.Navigation.csproj" />
	</ItemGroup>
</Project>
