<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net481;net9.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Navigation\NekoLib.Navigation.WinForms\NekoLib.Navigation.WinForms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WindowsFormsIntegration">
      <HintPath>..\..\..\..\..\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\AppLocalWPF\WindowsFormsIntegration.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages\ConfirmDialog.cs" />
  </ItemGroup>

</Project>