<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net481;net9-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\NekoLib.Diagnostics\NekoLib.Diagnostics.csproj" />
    <ProjectReference Include="..\..\..\NekoLib.Runtime.Watchdog\NekoLib.Runtime.Watchdog.Core\NekoLib.Runtime.Watchdog.Core.csproj" />
    <ProjectReference Include="..\..\..\NekoLib.Runtime.Watchdog\NekoLib.Runtime.Watchdog.Host\WatchdogHost\WatchdogHost.csproj" />
  </ItemGroup>
<PropertyGroup Condition="'$(TargetFramework)' == 'net481' &#xD;&#xA;                        Or '$(TargetFramework)' == 'net9.0-windows'">
  <DefineConstants>$(DefineConstants);WINFORMS</DefineConstants>
</PropertyGroup>

</Project>