<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net481;net9.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>NekoLib.Watchdog.RuntimeTests.CrashRecovery.Tests</RootNamespace>
    <AssemblyName>NekoLib.Watchdog.RuntimeTests.CrashRecovery.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NekoLib.Watchdog.RuntimeTests.CrashRecovery\NekoLib.Watchdog.RuntimeTests.CrashRecovery.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

</Project>
