<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net481;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>

    <IsPackable>true</IsPackable>
    <PackageId>NekoLib.Pipes</PackageId>
    <Title>NekoLib Pipes</Title>
    <Description>Named-pipe IPC with framed request-response RPC, pub-sub events and optional metrics.</Description>
    <PackageTags>nekolib;ipc;named-pipes;rpc;desktop</PackageTags>
  </PropertyGroup>

  <!-- Newtonsoft only for 481 -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
    <DefineConstants>NET481</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <DefineConstants>NET9</DefineConstants>
  </PropertyGroup>

</Project>
