<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net481;net9.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Newtonsoft only for 481 -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
    <DefineConstants>NET481</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
    <DefineConstants>NET9</DefineConstants>
  </PropertyGroup>

</Project>
