<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>
 
		<!-- Library -->
		<OutputType>Library</OutputType>

		<!-- Assembly info -->
		<AssemblyName>NekoLib.Data</AssemblyName>
		<RootNamespace>NekoLib.Data</RootNamespace>

		<IsPackable>true</IsPackable>
		<PackageId>NekoLib.Data</PackageId>
		<Title>NekoLib Data</Title>
		<Description>Provider-neutral database gateway with fluent SQL building, typed and dynamic reads, streaming and transactions.</Description>
		<PackageTags>nekolib;data;database;sql;ado-net</PackageTags>
 
		<!-- Identity -->
		<DefineConstants>$(DefineConstants);NEKOLIB</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>$(DefineConstants);NET_9</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
		<DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net481'">
	  <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.1" />
	</ItemGroup>
</Project>
