<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net481;net9.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms Condition="'$(TargetFramework)' == 'net9.0-windows'">true</UseWindowsForms>
    <UseWPF Condition="'$(TargetFramework)' == 'net9.0-windows'">true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" Version="11.5.4" PrivateAssets="all" />
  </ItemGroup>
</Project>
