#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NekoLib.Data.Query 
{
    /// <summary>
    /// Provider-neutral SQL model produced by <see cref="QueryBuilder"/>.
    /// Contains base SQL, parameters, and translation metadata.
    /// </summary>
    public sealed class QueryModel
    {
        /// <summary>
        /// Gets the provider-neutral SQL generated by <see cref="QueryBuilder"/>.
        /// </summary>
        public string Sql { get; }

        /// <summary>
        /// Gets a read-only view of command parameters.
        /// </summary>
        public IReadOnlyDictionary<string, object?> Parameters { get; }

        /// <summary>
        /// Gets the requested row limit, interpreted by the provider translator.
        /// </summary>
        public int? Top { get; }

        /// <summary>Gets the provider-neutral command policy.</summary>
        public DbCommandPolicy CommandPolicy { get; }

        public QueryModel(
            string Sql,
            Dictionary<string, object?> Parameters,
            int? Top = null,
            DbCommandPolicy? CommandPolicy = null)
        {
            if (Sql == null) throw new ArgumentNullException(nameof(Sql));
            if (Parameters == null) throw new ArgumentNullException(nameof(Parameters));

            this.Sql = Sql;
            this.Parameters = new Dictionary<string, object?>(Parameters);
            this.Top = Top;
            this.CommandPolicy = CommandPolicy?.Copy() ?? new DbCommandPolicy();
            this.CommandPolicy.Validate(nameof(CommandPolicy));
        }
    }



    /// <summary>
    /// Translates a <see cref="QueryModel"/> into provider-specific
    /// <see cref="DatabaseQuery"/> instances.
    /// </summary>
    public interface IDbQueryTranslator
    {
        /// <summary>
        /// Translates a provider-neutral model into a provider-specific query.
        /// </summary>
        DatabaseQuery Translate(QueryModel Model);
    }
}
