<Project Sdk="Microsoft.NET.Sdk">


	<PropertyGroup>
		<TargetFrameworks>net481;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>

		<!-- Library -->
		<OutputType>Library</OutputType>
 
		<!-- Assembly info -->
		<AssemblyName>NekoLib</AssemblyName>
		<RootNamespace>NekoLib</RootNamespace>
		<!-- Identity -->
		<DefineConstants>$(DefineConstants);NEKOLIB</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>$(DefineConstants);NET_9</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
		<DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NekoLib.Core\NekoLib.Core.csproj" />
		<ProjectReference Include="..\NekoLib.Diagnostics.Abstractions\NekoLib.Diagnostics.Abstractions.csproj" />
		<ProjectReference Include="..\NekoLib.Diagnostics\NekoLib.Diagnostics.csproj" />
	</ItemGroup>
</Project>
