<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>
		
		<!-- Library -->
		<OutputType>Library</OutputType>

		<!-- Assembly info -->
		<AssemblyName>NekoLib.Core</AssemblyName>
		<RootNamespace>NekoLib.Core</RootNamespace>

		<!-- Identity -->
		<DefineConstants>$(DefineConstants);NEKOLIB</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>$(DefineConstants);NET_9</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
		<DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NekoLib.Diagnostics.Abstractions\NekoLib.Diagnostics.Abstractions.csproj" />
	</ItemGroup>

</Project>
