<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<OutputType>Library</OutputType>

		<AssemblyName>NekoLib.Devices</AssemblyName>
		<RootNamespace>NekoLib.Devices</RootNamespace>

		<IsPackable>true</IsPackable>
		<PackageId>NekoLib.Devices</PackageId>
		<Title>NekoLib Devices</Title>
		<Description>Serial-port, TCP, and named-pipe transports with hardware protocol abstractions for desktop and embedded applications.</Description>
		<PackageTags>nekolib;devices;serial-port;tcp;named-pipe;hardware;embedded</PackageTags>
	</PropertyGroup>

	<!-- Framework flags -->
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<DefineConstants>$(DefineConstants);NET_9</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
		<DefineConstants>$(DefineConstants);NETFRAMEWORK</DefineConstants>
	</PropertyGroup>

	<!-- net9 references -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="System.IO.Ports" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net481'">
	  <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.1" />
	</ItemGroup>

	<!-- Core -->

</Project>
